// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eg.proto

package pbfile

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// the status code can add when need
type CRS_STATUS int32

const (
	CRS_STATUS_CRS_SUCCESS CRS_STATUS = 0
	CRS_STATUS_CRS_FAIL    CRS_STATUS = 1
)

var CRS_STATUS_name = map[int32]string{
	0: "CRS_SUCCESS",
	1: "CRS_FAIL",
}

var CRS_STATUS_value = map[string]int32{
	"CRS_SUCCESS": 0,
	"CRS_FAIL":    1,
}

func (x CRS_STATUS) String() string {
	return proto.EnumName(CRS_STATUS_name, int32(x))
}

func (CRS_STATUS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6f2eeaba6920296f, []int{0}
}

// charging data req type, must be same with smf
type ChargingReqType int32

const (
	ChargingReqType_unknow  ChargingReqType = 0
	ChargingReqType_create  ChargingReqType = 1
	ChargingReqType_update  ChargingReqType = 2
	ChargingReqType_release ChargingReqType = 3
)

var ChargingReqType_name = map[int32]string{
	0: "unknow",
	1: "create",
	2: "update",
	3: "release",
}

var ChargingReqType_value = map[string]int32{
	"unknow":  0,
	"create":  1,
	"update":  2,
	"release": 3,
}

func (x ChargingReqType) String() string {
	return proto.EnumName(ChargingReqType_name, int32(x))
}

func (ChargingReqType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6f2eeaba6920296f, []int{1}
}

// nchf api version
type NchfApiVersion int32

const (
	NchfApiVersion_V1 NchfApiVersion = 0
	NchfApiVersion_V2 NchfApiVersion = 1
)

var NchfApiVersion_name = map[int32]string{
	0: "V1",
	1: "V2",
}

var NchfApiVersion_value = map[string]int32{
	"V1": 0,
	"V2": 1,
}

func (x NchfApiVersion) String() string {
	return proto.EnumName(NchfApiVersion_name, int32(x))
}

func (NchfApiVersion) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6f2eeaba6920296f, []int{2}
}

type StoreChargingRecordReqMsg struct {
	ChargingId           uint32         `protobuf:"varint,1,opt,name=chargingId,proto3" json:"chargingId,omitempty"`
	PrimaryChfAddress    string         `protobuf:"bytes,2,opt,name=primaryChfAddress,proto3" json:"primaryChfAddress,omitempty"`
	SecondaryChfAddress  string         `protobuf:"bytes,3,opt,name=secondaryChfAddress,proto3" json:"secondaryChfAddress,omitempty"`
	ChargingReference    string         `protobuf:"bytes,4,opt,name=chargingReference,proto3" json:"chargingReference,omitempty"`
	ChargingDataReqSlice []*ChargingReq `protobuf:"bytes,5,rep,name=chargingDataReqSlice,proto3" json:"chargingDataReqSlice,omitempty"`
	NchfApiVersion       NchfApiVersion `protobuf:"varint,6,opt,name=nchfApiVersion,proto3,enum=crs.NchfApiVersion" json:"nchfApiVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *StoreChargingRecordReqMsg) Reset()         { *m = StoreChargingRecordReqMsg{} }
func (m *StoreChargingRecordReqMsg) String() string { return proto.CompactTextString(m) }
func (*StoreChargingRecordReqMsg) ProtoMessage()    {}
func (*StoreChargingRecordReqMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f2eeaba6920296f, []int{0}
}

func (m *StoreChargingRecordReqMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreChargingRecordReqMsg.Unmarshal(m, b)
}
func (m *StoreChargingRecordReqMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreChargingRecordReqMsg.Marshal(b, m, deterministic)
}
func (m *StoreChargingRecordReqMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreChargingRecordReqMsg.Merge(m, src)
}
func (m *StoreChargingRecordReqMsg) XXX_Size() int {
	return xxx_messageInfo_StoreChargingRecordReqMsg.Size(m)
}
func (m *StoreChargingRecordReqMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreChargingRecordReqMsg.DiscardUnknown(m)
}

var xxx_messageInfo_StoreChargingRecordReqMsg proto.InternalMessageInfo

func (m *StoreChargingRecordReqMsg) GetChargingId() uint32 {
	if m != nil {
		return m.ChargingId
	}
	return 0
}

func (m *StoreChargingRecordReqMsg) GetPrimaryChfAddress() string {
	if m != nil {
		return m.PrimaryChfAddress
	}
	return ""
}

func (m *StoreChargingRecordReqMsg) GetSecondaryChfAddress() string {
	if m != nil {
		return m.SecondaryChfAddress
	}
	return ""
}

func (m *StoreChargingRecordReqMsg) GetChargingReference() string {
	if m != nil {
		return m.ChargingReference
	}
	return ""
}

func (m *StoreChargingRecordReqMsg) GetChargingDataReqSlice() []*ChargingReq {
	if m != nil {
		return m.ChargingDataReqSlice
	}
	return nil
}

func (m *StoreChargingRecordReqMsg) GetNchfApiVersion() NchfApiVersion {
	if m != nil {
		return m.NchfApiVersion
	}
	return NchfApiVersion_V1
}

type NotifyChfAvailabilityReqMsg struct {
	ChfAddress           string   `protobuf:"bytes,1,opt,name=chfAddress,proto3" json:"chfAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyChfAvailabilityReqMsg) Reset()         { *m = NotifyChfAvailabilityReqMsg{} }
func (m *NotifyChfAvailabilityReqMsg) String() string { return proto.CompactTextString(m) }
func (*NotifyChfAvailabilityReqMsg) ProtoMessage()    {}
func (*NotifyChfAvailabilityReqMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f2eeaba6920296f, []int{1}
}

func (m *NotifyChfAvailabilityReqMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyChfAvailabilityReqMsg.Unmarshal(m, b)
}
func (m *NotifyChfAvailabilityReqMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyChfAvailabilityReqMsg.Marshal(b, m, deterministic)
}
func (m *NotifyChfAvailabilityReqMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyChfAvailabilityReqMsg.Merge(m, src)
}
func (m *NotifyChfAvailabilityReqMsg) XXX_Size() int {
	return xxx_messageInfo_NotifyChfAvailabilityReqMsg.Size(m)
}
func (m *NotifyChfAvailabilityReqMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyChfAvailabilityReqMsg.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyChfAvailabilityReqMsg proto.InternalMessageInfo

func (m *NotifyChfAvailabilityReqMsg) GetChfAddress() string {
	if m != nil {
		return m.ChfAddress
	}
	return ""
}

type CommonRspMsg struct {
	Result               CRS_STATUS `protobuf:"varint,1,opt,name=result,proto3,enum=crs.CRS_STATUS" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CommonRspMsg) Reset()         { *m = CommonRspMsg{} }
func (m *CommonRspMsg) String() string { return proto.CompactTextString(m) }
func (*CommonRspMsg) ProtoMessage()    {}
func (*CommonRspMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f2eeaba6920296f, []int{2}
}

func (m *CommonRspMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonRspMsg.Unmarshal(m, b)
}
func (m *CommonRspMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonRspMsg.Marshal(b, m, deterministic)
}
func (m *CommonRspMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonRspMsg.Merge(m, src)
}
func (m *CommonRspMsg) XXX_Size() int {
	return xxx_messageInfo_CommonRspMsg.Size(m)
}
func (m *CommonRspMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonRspMsg.DiscardUnknown(m)
}

var xxx_messageInfo_CommonRspMsg proto.InternalMessageInfo

func (m *CommonRspMsg) GetResult() CRS_STATUS {
	if m != nil {
		return m.Result
	}
	return CRS_STATUS_CRS_SUCCESS
}

type ChargingReq struct {
	FailReq              []byte          `protobuf:"bytes,1,opt,name=failReq,proto3" json:"failReq,omitempty"`
	ReqType              ChargingReqType `protobuf:"varint,2,opt,name=reqType,proto3,enum=crs.ChargingReqType" json:"reqType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ChargingReq) Reset()         { *m = ChargingReq{} }
func (m *ChargingReq) String() string { return proto.CompactTextString(m) }
func (*ChargingReq) ProtoMessage()    {}
func (*ChargingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f2eeaba6920296f, []int{3}
}

func (m *ChargingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChargingReq.Unmarshal(m, b)
}
func (m *ChargingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChargingReq.Marshal(b, m, deterministic)
}
func (m *ChargingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChargingReq.Merge(m, src)
}
func (m *ChargingReq) XXX_Size() int {
	return xxx_messageInfo_ChargingReq.Size(m)
}
func (m *ChargingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChargingReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChargingReq proto.InternalMessageInfo

func (m *ChargingReq) GetFailReq() []byte {
	if m != nil {
		return m.FailReq
	}
	return nil
}

func (m *ChargingReq) GetReqType() ChargingReqType {
	if m != nil {
		return m.ReqType
	}
	return ChargingReqType_unknow
}

func init() {
	proto.RegisterEnum("crs.CRS_STATUS", CRS_STATUS_name, CRS_STATUS_value)
	proto.RegisterEnum("crs.ChargingReqType", ChargingReqType_name, ChargingReqType_value)
	proto.RegisterEnum("crs.NchfApiVersion", NchfApiVersion_name, NchfApiVersion_value)
	proto.RegisterType((*StoreChargingRecordReqMsg)(nil), "crs.StoreChargingRecordReqMsg")
	proto.RegisterType((*NotifyChfAvailabilityReqMsg)(nil), "crs.NotifyChfAvailabilityReqMsg")
	proto.RegisterType((*CommonRspMsg)(nil), "crs.CommonRspMsg")
	proto.RegisterType((*ChargingReq)(nil), "crs.ChargingReq")
}

func init() { proto.RegisterFile("eg.proto", fileDescriptor_6f2eeaba6920296f) }

var fileDescriptor_6f2eeaba6920296f = []byte{
	// 474 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x6d, 0x5a, 0xc8, 0xc6, 0x6d, 0x49, 0x33, 0x77, 0x48, 0x01, 0xa4, 0x29, 0xca, 0x0b, 0x55,
	0x41, 0x15, 0x84, 0x07, 0x1e, 0x10, 0x0f, 0x5d, 0x06, 0xd2, 0x10, 0xf4, 0xc1, 0xe9, 0x86, 0xc4,
	0x0b, 0x4a, 0x9d, 0x9b, 0xd6, 0x22, 0x8d, 0x13, 0x3b, 0x1b, 0xea, 0x1f, 0xf1, 0x31, 0x7c, 0x14,
	0x8a, 0xbb, 0x6e, 0x69, 0x97, 0x3d, 0xc5, 0x3e, 0xe7, 0xf8, 0xc6, 0xe7, 0x9e, 0x6b, 0x38, 0xc4,
	0xc5, 0x38, 0x97, 0xa2, 0x14, 0xa4, 0xc3, 0xa4, 0xf2, 0xfe, 0xb5, 0xe1, 0x79, 0x58, 0x0a, 0x89,
	0xc1, 0x32, 0x92, 0x0b, 0x9e, 0x2d, 0x28, 0x32, 0x21, 0x63, 0x8a, 0xc5, 0x77, 0xb5, 0x20, 0x27,
	0x00, 0xec, 0x06, 0x3f, 0x8f, 0x1d, 0xc3, 0x35, 0x86, 0x4f, 0x69, 0x0d, 0x21, 0x6f, 0xe0, 0x28,
	0x97, 0x7c, 0x15, 0xc9, 0x75, 0xb0, 0x4c, 0x26, 0x71, 0x2c, 0x51, 0x29, 0xa7, 0xed, 0x1a, 0xc3,
	0x27, 0xf4, 0x3e, 0x41, 0xde, 0xc2, 0x40, 0x21, 0x13, 0x59, 0xbc, 0xab, 0xef, 0x68, 0x7d, 0x13,
	0x55, 0xd5, 0x67, 0xb7, 0xf7, 0x4a, 0x50, 0x62, 0xc6, 0xd0, 0x79, 0xb4, 0xa9, 0x7f, 0x8f, 0x20,
	0x67, 0x70, 0xbc, 0x05, 0xcf, 0xa2, 0x32, 0xa2, 0x58, 0x84, 0x29, 0x67, 0xe8, 0x3c, 0x76, 0x3b,
	0xc3, 0xae, 0x6f, 0x8f, 0x99, 0x54, 0xe3, 0x3b, 0x9b, 0x05, 0x6d, 0x54, 0x93, 0x8f, 0x60, 0x65,
	0x6c, 0x99, 0x4c, 0x72, 0x7e, 0x89, 0x52, 0x71, 0x91, 0x39, 0xa6, 0x6b, 0x0c, 0x2d, 0x7f, 0xa0,
	0xcf, 0x4f, 0x77, 0x28, 0xba, 0x27, 0xf5, 0x3e, 0xc1, 0xcb, 0xa9, 0x28, 0x79, 0xa2, 0x4d, 0x5c,
	0x47, 0x3c, 0x8d, 0xe6, 0x3c, 0xe5, 0xe5, 0xba, 0xde, 0xcf, 0x5b, 0xe3, 0x86, 0x36, 0x52, 0x43,
	0xbc, 0x0f, 0xd0, 0x0b, 0xc4, 0x6a, 0x25, 0x32, 0xaa, 0xf2, 0x4a, 0xff, 0x0a, 0x4c, 0x89, 0xea,
	0x2a, 0x2d, 0xb5, 0xd6, 0xf2, 0xfb, 0x1b, 0x0f, 0x34, 0xfc, 0x15, 0xce, 0x26, 0xb3, 0x8b, 0x90,
	0xde, 0xd0, 0xde, 0x0f, 0xe8, 0xd6, 0x9c, 0x11, 0x07, 0x0e, 0x92, 0x88, 0xa7, 0x14, 0x0b, 0x7d,
	0xb0, 0x47, 0xb7, 0x5b, 0x32, 0x86, 0x03, 0x89, 0xc5, 0x6c, 0x9d, 0xa3, 0xce, 0xc9, 0xf2, 0x8f,
	0xf7, 0xdb, 0x52, 0x71, 0x74, 0x2b, 0x1a, 0xbd, 0x06, 0xb8, 0xfb, 0x1d, 0xe9, 0x43, 0x57, 0xef,
	0x2e, 0x82, 0xe0, 0x73, 0x18, 0xda, 0x2d, 0xd2, 0x83, 0xc3, 0x0a, 0xf8, 0x32, 0x39, 0xff, 0x66,
	0x1b, 0xa3, 0x53, 0xe8, 0xef, 0x15, 0x22, 0x00, 0xe6, 0x55, 0xf6, 0x3b, 0x13, 0x7f, 0xec, 0x56,
	0xb5, 0x66, 0x12, 0xa3, 0x12, 0x6d, 0x43, 0xe3, 0x79, 0x5c, 0xad, 0xdb, 0xa4, 0x5b, 0xdd, 0x29,
	0xc5, 0x48, 0xa1, 0xdd, 0x19, 0xb9, 0x60, 0xed, 0xf6, 0x98, 0x98, 0xd0, 0xbe, 0x7c, 0x67, 0xb7,
	0xf4, 0xd7, 0xb7, 0x0d, 0xff, 0xaf, 0x01, 0x10, 0x48, 0x15, 0xa2, 0xbc, 0xae, 0xf2, 0xfa, 0x0a,
	0x83, 0x86, 0x01, 0x26, 0x27, 0xda, 0xd7, 0x83, 0xa3, 0xfd, 0xe2, 0x68, 0xe3, 0xbb, 0xd6, 0x6d,
	0xaf, 0x45, 0xa6, 0xf0, 0xac, 0x31, 0x3e, 0xe2, 0x6e, 0xc2, 0x7f, 0x38, 0xda, 0xc6, 0x7a, 0xa7,
	0x87, 0x3f, 0xcd, 0x7c, 0x9e, 0xf0, 0x14, 0xe7, 0xa6, 0x7e, 0x73, 0xef, 0xff, 0x07, 0x00, 0x00,
	0xff, 0xff, 0x71, 0x0a, 0xa5, 0xd5, 0x7f, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CrsServiceClient is the client API for CrsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CrsServiceClient interface {
	StoreChargingRecord(ctx context.Context, in *StoreChargingRecordReqMsg, opts ...grpc.CallOption) (*CommonRspMsg, error)
	NotifyChfAvailability(ctx context.Context, in *NotifyChfAvailabilityReqMsg, opts ...grpc.CallOption) (*CommonRspMsg, error)
}

type crsServiceClient struct {
	cc *grpc.ClientConn
}

func NewCrsServiceClient(cc *grpc.ClientConn) CrsServiceClient {
	return &crsServiceClient{cc}
}

func (c *crsServiceClient) StoreChargingRecord(ctx context.Context, in *StoreChargingRecordReqMsg, opts ...grpc.CallOption) (*CommonRspMsg, error) {
	out := new(CommonRspMsg)
	err := c.cc.Invoke(ctx, "/crs.CrsService/StoreChargingRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crsServiceClient) NotifyChfAvailability(ctx context.Context, in *NotifyChfAvailabilityReqMsg, opts ...grpc.CallOption) (*CommonRspMsg, error) {
	out := new(CommonRspMsg)
	err := c.cc.Invoke(ctx, "/crs.CrsService/NotifyChfAvailability", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrsServiceServer is the server API for CrsService service.
type CrsServiceServer interface {
	StoreChargingRecord(context.Context, *StoreChargingRecordReqMsg) (*CommonRspMsg, error)
	NotifyChfAvailability(context.Context, *NotifyChfAvailabilityReqMsg) (*CommonRspMsg, error)
}

// UnimplementedCrsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCrsServiceServer struct {
}

func (*UnimplementedCrsServiceServer) StoreChargingRecord(ctx context.Context, req *StoreChargingRecordReqMsg) (*CommonRspMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreChargingRecord not implemented")
}
func (*UnimplementedCrsServiceServer) NotifyChfAvailability(ctx context.Context, req *NotifyChfAvailabilityReqMsg) (*CommonRspMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyChfAvailability not implemented")
}

func RegisterCrsServiceServer(s *grpc.Server, srv CrsServiceServer) {
	s.RegisterService(&_CrsService_serviceDesc, srv)
}

func _CrsService_StoreChargingRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreChargingRecordReqMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrsServiceServer).StoreChargingRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crs.CrsService/StoreChargingRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrsServiceServer).StoreChargingRecord(ctx, req.(*StoreChargingRecordReqMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrsService_NotifyChfAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyChfAvailabilityReqMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrsServiceServer).NotifyChfAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crs.CrsService/NotifyChfAvailability",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrsServiceServer).NotifyChfAvailability(ctx, req.(*NotifyChfAvailabilityReqMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _CrsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "crs.CrsService",
	HandlerType: (*CrsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreChargingRecord",
			Handler:    _CrsService_StoreChargingRecord_Handler,
		},
		{
			MethodName: "NotifyChfAvailability",
			Handler:    _CrsService_NotifyChfAvailability_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eg.proto",
}
