// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eg2_4.proto

package pbfile

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 枚举 enum
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_OK          Status = 1
	Status_STATUS_FAIL        Status = 10
)

var Status_name = map[int32]string{
	0:  "STATUS_UNSPECIFIED",
	1:  "STATUS_OK",
	10: "STATUS_FAIL",
}

var Status_value = map[string]int32{
	"STATUS_UNSPECIFIED": 0,
	"STATUS_OK":          1,
	"STATUS_FAIL":        10,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c8101c8e791a9449, []int{0}
}

type SearchResponse_Status int32

const (
	SearchResponse_UNSPECIFIED SearchResponse_Status = 0
	SearchResponse_OK          SearchResponse_Status = 1
	SearchResponse_FAIL        SearchResponse_Status = 2
)

var SearchResponse_Status_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "OK",
	2: "FAIL",
}

var SearchResponse_Status_value = map[string]int32{
	"UNSPECIFIED": 0,
	"OK":          1,
	"FAIL":        2,
}

func (x SearchResponse_Status) String() string {
	return proto.EnumName(SearchResponse_Status_name, int32(x))
}

func (SearchResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c8101c8e791a9449, []int{2, 0}
}

// 普通的message
type SearchRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	PageNumber           int32    `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	ResultPerPage        int32    `protobuf:"varint,3,opt,name=result_per_page,json=resultPerPage,proto3" json:"result_per_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8101c8e791a9449, []int{0}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SearchRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *SearchRequest) GetResultPerPage() int32 {
	if m != nil {
		return m.ResultPerPage
	}
	return 0
}

//保留字段 (Reserved Fields)
type ReservedMessage struct {
	Ffff string `protobuf:"bytes,1,opt,name=ffff,proto3" json:"ffff,omitempty"`
	// string abc = 2;  // 编译报错, 序号被复用
	// string foo = 3;  // 编译报错，字段名被复用
	Dddd                 string   `protobuf:"bytes,3,opt,name=dddd,proto3" json:"dddd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReservedMessage) Reset()         { *m = ReservedMessage{} }
func (m *ReservedMessage) String() string { return proto.CompactTextString(m) }
func (*ReservedMessage) ProtoMessage()    {}
func (*ReservedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8101c8e791a9449, []int{1}
}

func (m *ReservedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReservedMessage.Unmarshal(m, b)
}
func (m *ReservedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReservedMessage.Marshal(b, m, deterministic)
}
func (m *ReservedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReservedMessage.Merge(m, src)
}
func (m *ReservedMessage) XXX_Size() int {
	return xxx_messageInfo_ReservedMessage.Size(m)
}
func (m *ReservedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ReservedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ReservedMessage proto.InternalMessageInfo

func (m *ReservedMessage) GetFfff() string {
	if m != nil {
		return m.Ffff
	}
	return ""
}

func (m *ReservedMessage) GetDddd() string {
	if m != nil {
		return m.Dddd
	}
	return ""
}

// 嵌套message， enum
type SearchResponse struct {
	Results              *SearchResponse_Result `protobuf:"bytes,1,opt,name=results,proto3" json:"results,omitempty"`
	Status               SearchResponse_Status  `protobuf:"varint,2,opt,name=status,proto3,enum=exampleProto.SearchResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8101c8e791a9449, []int{2}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetResults() *SearchResponse_Result {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *SearchResponse) GetStatus() SearchResponse_Status {
	if m != nil {
		return m.Status
	}
	return SearchResponse_UNSPECIFIED
}

type SearchResponse_Result struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResponse_Result) Reset()         { *m = SearchResponse_Result{} }
func (m *SearchResponse_Result) String() string { return proto.CompactTextString(m) }
func (*SearchResponse_Result) ProtoMessage()    {}
func (*SearchResponse_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8101c8e791a9449, []int{2, 0}
}

func (m *SearchResponse_Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse_Result.Unmarshal(m, b)
}
func (m *SearchResponse_Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse_Result.Marshal(b, m, deterministic)
}
func (m *SearchResponse_Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse_Result.Merge(m, src)
}
func (m *SearchResponse_Result) XXX_Size() int {
	return xxx_messageInfo_SearchResponse_Result.Size(m)
}
func (m *SearchResponse_Result) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse_Result.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse_Result proto.InternalMessageInfo

func (m *SearchResponse_Result) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *SearchResponse_Result) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

//引用 嵌套的 Result
type OtherResponse struct {
	Result               *SearchResponse_Result `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Status               SearchResponse_Status  `protobuf:"varint,2,opt,name=status,proto3,enum=exampleProto.SearchResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *OtherResponse) Reset()         { *m = OtherResponse{} }
func (m *OtherResponse) String() string { return proto.CompactTextString(m) }
func (*OtherResponse) ProtoMessage()    {}
func (*OtherResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8101c8e791a9449, []int{3}
}

func (m *OtherResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OtherResponse.Unmarshal(m, b)
}
func (m *OtherResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OtherResponse.Marshal(b, m, deterministic)
}
func (m *OtherResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OtherResponse.Merge(m, src)
}
func (m *OtherResponse) XXX_Size() int {
	return xxx_messageInfo_OtherResponse.Size(m)
}
func (m *OtherResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OtherResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OtherResponse proto.InternalMessageInfo

func (m *OtherResponse) GetResult() *SearchResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *OtherResponse) GetStatus() SearchResponse_Status {
	if m != nil {
		return m.Status
	}
	return SearchResponse_UNSPECIFIED
}

// repeated proto file
type RepeatedMessage struct {
	Requests             []*SearchRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	Status               []Status         `protobuf:"varint,2,rep,packed,name=status,proto3,enum=exampleProto.Status" json:"status,omitempty"`
	Number               []int32          `protobuf:"varint,3,rep,packed,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RepeatedMessage) Reset()         { *m = RepeatedMessage{} }
func (m *RepeatedMessage) String() string { return proto.CompactTextString(m) }
func (*RepeatedMessage) ProtoMessage()    {}
func (*RepeatedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8101c8e791a9449, []int{4}
}

func (m *RepeatedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepeatedMessage.Unmarshal(m, b)
}
func (m *RepeatedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepeatedMessage.Marshal(b, m, deterministic)
}
func (m *RepeatedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepeatedMessage.Merge(m, src)
}
func (m *RepeatedMessage) XXX_Size() int {
	return xxx_messageInfo_RepeatedMessage.Size(m)
}
func (m *RepeatedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RepeatedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RepeatedMessage proto.InternalMessageInfo

func (m *RepeatedMessage) GetRequests() []*SearchRequest {
	if m != nil {
		return m.Requests
	}
	return nil
}

func (m *RepeatedMessage) GetStatus() []Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *RepeatedMessage) GetNumber() []int32 {
	if m != nil {
		return m.Number
	}
	return nil
}

// one of
type OneOfMessage struct {
	// Types that are valid to be assigned to TestOneof:
	//	*OneOfMessage_M1
	//	*OneOfMessage_M2
	TestOneof            isOneOfMessage_TestOneof `protobuf_oneof:"test_oneof"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *OneOfMessage) Reset()         { *m = OneOfMessage{} }
func (m *OneOfMessage) String() string { return proto.CompactTextString(m) }
func (*OneOfMessage) ProtoMessage()    {}
func (*OneOfMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8101c8e791a9449, []int{5}
}

func (m *OneOfMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OneOfMessage.Unmarshal(m, b)
}
func (m *OneOfMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OneOfMessage.Marshal(b, m, deterministic)
}
func (m *OneOfMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OneOfMessage.Merge(m, src)
}
func (m *OneOfMessage) XXX_Size() int {
	return xxx_messageInfo_OneOfMessage.Size(m)
}
func (m *OneOfMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_OneOfMessage.DiscardUnknown(m)
}

var xxx_messageInfo_OneOfMessage proto.InternalMessageInfo

type isOneOfMessage_TestOneof interface {
	isOneOfMessage_TestOneof()
}

type OneOfMessage_M1 struct {
	M1 string `protobuf:"bytes,1,opt,name=m1,proto3,oneof"`
}

type OneOfMessage_M2 struct {
	M2 int32 `protobuf:"varint,2,opt,name=m2,proto3,oneof"`
}

func (*OneOfMessage_M1) isOneOfMessage_TestOneof() {}

func (*OneOfMessage_M2) isOneOfMessage_TestOneof() {}

func (m *OneOfMessage) GetTestOneof() isOneOfMessage_TestOneof {
	if m != nil {
		return m.TestOneof
	}
	return nil
}

func (m *OneOfMessage) GetM1() string {
	if x, ok := m.GetTestOneof().(*OneOfMessage_M1); ok {
		return x.M1
	}
	return ""
}

func (m *OneOfMessage) GetM2() int32 {
	if x, ok := m.GetTestOneof().(*OneOfMessage_M2); ok {
		return x.M2
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*OneOfMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*OneOfMessage_M1)(nil),
		(*OneOfMessage_M2)(nil),
	}
}

func init() {
	proto.RegisterEnum("exampleProto.Status", Status_name, Status_value)
	proto.RegisterEnum("exampleProto.SearchResponse_Status", SearchResponse_Status_name, SearchResponse_Status_value)
	proto.RegisterType((*SearchRequest)(nil), "exampleProto.SearchRequest")
	proto.RegisterType((*ReservedMessage)(nil), "exampleProto.ReservedMessage")
	proto.RegisterType((*SearchResponse)(nil), "exampleProto.SearchResponse")
	proto.RegisterType((*SearchResponse_Result)(nil), "exampleProto.SearchResponse.Result")
	proto.RegisterType((*OtherResponse)(nil), "exampleProto.OtherResponse")
	proto.RegisterType((*RepeatedMessage)(nil), "exampleProto.RepeatedMessage")
	proto.RegisterType((*OneOfMessage)(nil), "exampleProto.OneOfMessage")
}

func init() { proto.RegisterFile("eg2_4.proto", fileDescriptor_c8101c8e791a9449) }

var fileDescriptor_c8101c8e791a9449 = []byte{
	// 487 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0xdd, 0x7c, 0x34, 0x26, 0x37, 0x6d, 0x13, 0x86, 0x65, 0x29, 0xfa, 0x60, 0x89, 0x20, 0x41,
	0xa5, 0xb8, 0x51, 0xf0, 0x61, 0x11, 0x76, 0x57, 0x77, 0xb1, 0x55, 0xb7, 0x65, 0xb2, 0x7d, 0xf1,
	0x25, 0xa4, 0xe6, 0xa6, 0x2b, 0xb4, 0x49, 0x76, 0x66, 0x22, 0xfa, 0x13, 0x7c, 0xf3, 0x7f, 0xfa,
	0x27, 0x24, 0x33, 0x69, 0x6d, 0x45, 0x10, 0xf1, 0x6d, 0xee, 0xc9, 0xb9, 0x67, 0xee, 0x99, 0x73,
	0x03, 0x2e, 0x2e, 0xa3, 0xe4, 0xf9, 0xa8, 0x62, 0xa5, 0x28, 0x49, 0x17, 0xbf, 0xa4, 0xeb, 0x6a,
	0x85, 0xb3, 0xa6, 0x0a, 0x0a, 0xe8, 0xc5, 0x98, 0xb2, 0x8f, 0x37, 0x14, 0x6f, 0x6b, 0xe4, 0x82,
	0x1c, 0x42, 0xe7, 0xb6, 0x46, 0xf6, 0x75, 0xa0, 0x0d, 0xb5, 0xd0, 0xa1, 0xaa, 0x20, 0xf7, 0xc1,
	0xad, 0xd2, 0x25, 0x26, 0x45, 0xbd, 0x5e, 0x20, 0x1b, 0xe8, 0x43, 0x2d, 0xec, 0x50, 0x68, 0xa0,
	0x2b, 0x89, 0x90, 0x87, 0xe0, 0x31, 0xe4, 0xf5, 0x4a, 0x24, 0x15, 0xb2, 0xa4, 0xf9, 0x30, 0x30,
	0x24, 0xa9, 0xa7, 0xe0, 0x19, 0xb2, 0x59, 0xba, 0xc4, 0x60, 0x0e, 0x1e, 0x45, 0x8e, 0xec, 0x33,
	0x66, 0xef, 0x91, 0xf3, 0x74, 0x89, 0x84, 0x80, 0x99, 0xe7, 0x79, 0xde, 0x5e, 0x28, 0xcf, 0x0d,
	0x96, 0x65, 0x59, 0x26, 0x35, 0x1c, 0x2a, 0xcf, 0x13, 0xd3, 0xd6, 0x7d, 0x63, 0x62, 0xda, 0x9e,
	0xef, 0x4f, 0x4c, 0xdb, 0xf1, 0xbb, 0xd4, 0xc8, 0xcb, 0x92, 0x1a, 0x8b, 0x94, 0x05, 0x3f, 0x34,
	0xe8, 0x6f, 0x7c, 0xf0, 0xaa, 0x2c, 0x38, 0x92, 0x97, 0x70, 0x47, 0x5d, 0xcd, 0xa5, 0xb2, 0x1b,
	0x3d, 0x18, 0xed, 0x3a, 0x1f, 0xed, 0xd3, 0x47, 0x54, 0x72, 0xe9, 0xa6, 0x87, 0x9c, 0x80, 0xc5,
	0x45, 0x2a, 0x6a, 0x2e, 0xcd, 0xf6, 0xff, 0xd2, 0x1d, 0x4b, 0x2a, 0x6d, 0x5b, 0xee, 0x3e, 0x05,
	0x4b, 0xe9, 0x11, 0x1f, 0x8c, 0x9a, 0xad, 0x5a, 0x6f, 0xcd, 0xb1, 0x79, 0x60, 0xf1, 0x49, 0xac,
	0x50, 0xea, 0x3a, 0x54, 0x15, 0xc1, 0x63, 0xb0, 0x94, 0x06, 0xf1, 0xc0, 0x9d, 0x5f, 0xc5, 0xb3,
	0x8b, 0x57, 0xe3, 0xcb, 0xf1, 0xc5, 0x6b, 0xff, 0x80, 0x58, 0xa0, 0x4f, 0xdf, 0xfa, 0x1a, 0xb1,
	0xc1, 0xbc, 0x3c, 0x1b, 0xbf, 0xf3, 0xf5, 0xe0, 0x9b, 0x06, 0xbd, 0xa9, 0xb8, 0x41, 0xb6, 0x35,
	0x7b, 0x02, 0x96, 0x1a, 0xfc, 0x5f, 0xbc, 0xb6, 0x2d, 0xff, 0x65, 0x35, 0xf8, 0xae, 0x35, 0x89,
	0x56, 0x98, 0x8a, 0x5f, 0x89, 0xbe, 0x00, 0x9b, 0xa9, 0x75, 0x6a, 0xde, 0xde, 0x08, 0xdd, 0xe8,
	0xde, 0x9f, 0x25, 0x25, 0x87, 0x6e, 0xc9, 0xe4, 0xc9, 0xce, 0x24, 0x46, 0xd8, 0x8f, 0x0e, 0x7f,
	0x6b, 0xdb, 0xbb, 0x9a, 0x1c, 0x81, 0xd5, 0xee, 0xa3, 0x31, 0x34, 0xc2, 0x0e, 0x6d, 0xab, 0xe0,
	0x14, 0xba, 0xd3, 0x02, 0xa7, 0xf9, 0x66, 0x1c, 0x1f, 0xf4, 0xf5, 0xb1, 0x8a, 0xe0, 0xcd, 0x01,
	0xd5, 0xd7, 0xc7, 0x12, 0x89, 0xd4, 0x16, 0x4b, 0x24, 0x3a, 0xef, 0x02, 0x08, 0xe4, 0x22, 0x29,
	0x0b, 0x2c, 0xf3, 0x47, 0xa7, 0xdb, 0x34, 0x8e, 0x80, 0xc4, 0xd7, 0x67, 0xd7, 0xf3, 0x38, 0xd9,
	0x0f, 0xa5, 0x07, 0x4e, 0x8b, 0xcb, 0x6c, 0x3c, 0x70, 0xdb, 0x52, 0x46, 0x04, 0xe7, 0xee, 0x07,
	0x67, 0x33, 0xfa, 0x62, 0x61, 0xc9, 0x3f, 0xef, 0xd9, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa5,
	0xd0, 0x54, 0xd4, 0x88, 0x03, 0x00, 0x00,
}
